# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    schedule:
    - cron: '22 18 * * *' # every hour
  #push:
    #branches:
      #- master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: echo "Test"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy
        run: echo "Deploy"
