# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Runs a single command using the runners shell
      - name: Build
        run: echo "Build"


    test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: echo "Test"

    deploy:
    runs-on: ubuntu-latest
    needs: test

    steeps:
    
      - name: Deploy
        run: echo "Deploy"
        
