name: Semgrep

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config=auto .
